// <auto-generated />
using System;
using GestionEquipes.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionEquipes.Infrastructure.Migrations
{
    [DbContext(typeof(GestionEquipesContext))]
    partial class GestionEquipesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionEquipes.ApplicationCore.Domain.Contrat", b =>
                {
                    b.Property<DateTime>("DateContrat")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipeFk")
                        .HasColumnType("int");

                    b.Property<int>("MembreFk")
                        .HasColumnType("int");

                    b.Property<int>("DureeMois")
                        .HasColumnType("int");

                    b.Property<int>("Identifiant")
                        .HasColumnType("int");

                    b.Property<double>("Salaire")
                        .HasColumnType("float");

                    b.HasKey("DateContrat", "EquipeFk", "MembreFk");

                    b.HasIndex("EquipeFk");

                    b.HasIndex("MembreFk");

                    b.ToTable("Contrat");
                });

            modelBuilder.Entity("GestionEquipes.ApplicationCore.Domain.Equipe", b =>
                {
                    b.Property<int>("EquipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipeId"));

                    b.Property<string>("AdresseLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomEquipe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipeId");

                    b.ToTable("Equipe");
                });

            modelBuilder.Entity("GestionEquipes.ApplicationCore.Domain.Membre", b =>
                {
                    b.Property<int>("Identifiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identifiant"));

                    b.Property<DateTime>("DateNaisssance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identifiant");

                    b.ToTable("Membre");

                    b.HasDiscriminator<string>("Type").HasValue("M");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GestionEquipes.ApplicationCore.Domain.Trophee", b =>
                {
                    b.Property<int>("TropheeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TropheeId"));

                    b.Property<DateTime>("DateTrophee")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipeFK")
                        .HasColumnType("int");

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<double>("Recompense")
                        .HasColumnType("float");

                    b.Property<string>("TypeTrophee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TropheeId");

                    b.HasIndex("EquipeId");

                    b.ToTable("Trophee");
                });

            modelBuilder.Entity("GestionEquipes.ApplicationCore.Domain.Entraineur", b =>
                {
                    b.HasBaseType("GestionEquipes.ApplicationCore.Domain.Membre");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("E");
                });

            modelBuilder.Entity("GestionEquipes.ApplicationCore.Domain.Joueur", b =>
                {
                    b.HasBaseType("GestionEquipes.ApplicationCore.Domain.Membre");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("J");
                });

            modelBuilder.Entity("GestionEquipes.ApplicationCore.Domain.Contrat", b =>
                {
                    b.HasOne("GestionEquipes.ApplicationCore.Domain.Equipe", "Equipe")
                        .WithMany("Contrats")
                        .HasForeignKey("EquipeFk")
                        .IsRequired();

                    b.HasOne("GestionEquipes.ApplicationCore.Domain.Membre", "Membre")
                        .WithMany("Contrats")
                        .HasForeignKey("MembreFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("GestionEquipes.ApplicationCore.Domain.Trophee", b =>
                {
                    b.HasOne("GestionEquipes.ApplicationCore.Domain.Equipe", "Equipe")
                        .WithMany("Trophees")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("GestionEquipes.ApplicationCore.Domain.Equipe", b =>
                {
                    b.Navigation("Contrats");

                    b.Navigation("Trophees");
                });

            modelBuilder.Entity("GestionEquipes.ApplicationCore.Domain.Membre", b =>
                {
                    b.Navigation("Contrats");
                });
#pragma warning restore 612, 618
        }
    }
}
